### ISSUE TITLE
Refdiff plugin not working on master

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#1118]
@All I am having trouble with the refDiff plugin.
This is my cUrl: 
```
curl --location --request POST 'localhost:8080/pipelines' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "test-all",
    "tasks": [
        [
            {
                "Plugin": "refdiff",
                "Options": {
                    "repoId": "github:GithubRepository:384111310",
                    "pairs": [
                        {
                            "newRef": "v5.3.0",
                            "oldRef": "v5.2.3"
                        },
                        {
                            "newRef": "v5.2.0",
                            "oldRef": "v5.1.1"
                        }
                    ]
                }
            }
        ]
    ]
}'
```

But I get it failing like this:

```
 [GIN] 2022/01/25 - 15:13:49 | 201 |   22.396268ms |             ::1 | POST     "/pipelines"
INFO[2096] [INFO >>> run task in background  - /Users/jonathanodonnell/go/src/github.com/merico-dev/lake/services/pipeline.go:164 - 3
INFO[2096] [INFO >>> start executing task  - /Users/jonathanodonnell/go/src/github.com/merico-dev/lake/services/task.go:177 - 3
ERRO[2096] [ERROR >>> pipeline task failed - /Users/jonathanodonnell/go/src/github.com/merico-dev/lake/services/pipeline.go:172 - failed to load commit sha for NewRef on pair #0: faild to load Ref info for github:GithubRepository:384111310:v5.3.0
INFO[2096] [INFO >>> pipeline finished: - /Users/jonathanodonnell/go/src/github.com/merico-dev/lake/services/pipeline.go:194 - false
```

I also tried fully collecting my github data first. Even after full collection and truncating all my tables, it is still not working for me

The same error happnes if you pass in commit shas instead of tags

```
ERRO[3770] [ERROR >>> pipeline task failed - /Users/jonathanodonnell/go/src/github.com/merico-dev/lake/services/pipeline.go:172 - failed to load commit sha for NewRef on pair #0: faild to load Ref info for github:GithubRepository:384111310:11f4ca802083ee38d5972730ba8f9b72395316fb
INFO[3770] [INFO >>> pipeline finished: - /Users/jonathanodonnell/go/src/github.com/merico-dev/lake/services/pipeline.go:194 - false
```

I have github commits in my db
<img width="749" alt="Screen Shot 2022-01-25 at 5 18 44 PM" src="https://user-images.githubusercontent.com/3011407/151061451-8bd35020-13e7-451b-b26e-2f26d71a3212.png">

But no commits in the domain layer. I am re-running collection now to test why i got no commits in domain layer

<img width="1113" alt="Screen Shot 2022-01-25 at 5 19 26 PM" src="https://user-images.githubusercontent.com/3011407/151061577-c8ae88a0-f086-401c-81a2-b8be564389e6.png">

@klesh I am done for today but maybe you can provide more info tomorrow

**Comment by klesh** [comment]
I updated the README with more accurate description, please following the new guide and try again

**Comment by joncodo** [comment]
Still not working after DB reset, full collection and then running this JSON

```
"Plugin": "refdiff",
                "Options": {
                    "repoId": "github:GithubRepository:384111310",
                    "pairs": [
                        {
                            "newRef": "refs/tags/v0.6.0",
                            "oldRef": "refs/tags/v0.5.0"
                        }
                    ]
                }
```

Error: (No refs in my db but I do have commits)

```
INFO[6126] [INFO >>> start executing task  - /Users/jonathanodonnell/go/src/github.com/merico-dev/lake/services/task.go:177 - 15
ERRO[6126] [ERROR >>> pipeline task failed - /Users/jonathanodonnell/go/src/github.com/merico-dev/lake/services/pipeline.go:172 - failed to load commit sha for NewRef on pair #0: faild to load Ref info for github:GithubRepository:384111310:refs/tags/v0.6.0
```

**Comment by joncodo** [comment]
So now I have refs in my refs table:
<img width="1189" alt="Screen Shot 2022-01-26 at 4 23 36 PM" src="https://user-images.githubusercontent.com/3011407/151241060-ae5ef4df-4cec-4f50-820c-49aba4b7730c.png">

And I am doing this request:

```
curl --location --request POST 'localhost:8080/pipelines' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "test-all",
    "tasks": [
        [
            {
                "Plugin": "refdiff",
                "Options": {
                    "repoId": "github:GithubRepository:384111310",
                    "pairs": [
                        {
                            "newRef": "refs/tags/v0.6.0",
                            "oldRef": "refs/tags/v0.4.0"
                        }
                    ]
                }
            }
        ]
    ]
}'
```

Both refs exist in my DB

Error:

```
ERRO[0332] [ERROR >>> pipeline task failed - /Users/jonathanodonnell/go/src/github.com/merico-dev/lake/services/pipeline.go:172 - failed to load commit sha for NewRef on pair #0: faild to load Ref info for repoId:github:GithubRepository:384111310, refName:refs/tags/v0.6.0
```

**Comment by joncodo** [comment]
Note: I had to run gitextractor before refdiff plugins

**Comment by joncodo** [comment]
It worked when I changed 

`"repoId": "github:GithubRepository:384111310",` to `"repoId": "github:GithubRepos:384111310",`

I think this means that all our docs need to updated with this change as well


Output:
```
INFO[0069] [INFO >>> run task in background  - /Users/jonathanodonnell/go/src/github.com/merico-dev/lake/services/pipeline.go:164 - 20
INFO[0069] [INFO >>> start executing task  - /Users/jonathanodonnell/go/src/github.com/merico-dev/lake/services/task.go:177 - 20
JON >>> ref.Id github:GithubRepos:384111310:refs/tags/v0.6.0
JON >>> ref.Id github:GithubRepos:384111310:refs/tags/v0.4.0
INFO[0071] [INFO >>> refdiff - /Users/jonathanodonnell/go/src/github.com/merico-dev/lake/plugins/refdiff/refdiff.go:179 - total 360 commits of difference found between cbc7be53f5225e052c6aa6544ff6d8a582cb0959 and 088c3bdefac0fbbb63b842bf8466d687877cc94b
INFO[0071] [INFO >>> pipeline finished: - /Users/jonathanodonnell/go/src/github.com/merico-dev/lake/services/pipeline.go:194 - true
```
